version: "3.8"

services:
  app:
    build:
      context: app
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3000:3000"
    environment:
      NUXT_PUBLIC_API_BASE_URL_SERVER: http://pocketbase:8080
      NUXT_PUBLIC_API_BASE_URL_CLIENT: http://127.0.0.1:8080
    volumes:
      - ./app:/app
      - /app/node_modules
    networks:
      - leihbar

  pocketbase:
    build:
      context: pocketbase
      dockerfile: Dockerfile
      target: dev
    ports:
      - "8080:8080"
    volumes:
      - ./pocketbase/pb_migrations:/pb/pb_migrations
      - ./pocketbase/pb_data:/pb/pb_data
    networks:
      - leihbar

networks:
  leihbar:
