version: "3.8"

services:

  app:
    build:
      context: .
      dockerfile: node.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./app/:/app
      - /app/node_modules
    networks:
      - leihbar

  pocketbase:
    build:
      context: .
      dockerfile: pocketbase.Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./pocketbase/pb_migrations:/pb/pb_migrations
      - ./pocketbase/pb_data:/pb/pb_data
    networks:
      - leihbar


networks:
  leihbar: