app = 'leihbar-leihbase'
primary_region = 'ams'

[build]
  build-target = 'prod'

[env]
  NUXT_PUBLIC_POCKETBASE_CLIENT_BASE_URL = 'https://leihbar-pocketbase.fly.dev'
  NUXT_PUBLIC_POCKETBASE_SERVER_BASE_URL = 'http://leihbar-pocketbase.flycast'
  NUXT_PUBLIC_LAUSIBLE_TRACKING_DOMAIN = 'katalog.leihbar-koeln.org'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
